### ISSUE TITLE
Old custom domain still redirecting to pages

### ISSUE THREAD

**Issue by m5rilo** [Awes0meDev/code#1]
Hello. I was just using my old domain (awes0me.dev) to do something else with it (nothing to do with this repo), and every time I open the domain, it just redirects back to my site. I remember I used this domain a long time ago for this page, but changed my mind about it and used a different domain. Has been happening for a couple days now. Anyone know what I should do?

**Comment by m5rilo** [comment]
I have found no CNAME file with the old domain, and I have checked the DNS and found nothing that could be redirecting to my site.

**Comment by AlemDevCo** [comment]
Thats sad man. Can you send me a screenshot? I’m good with CNAMES.

**Comment by hgoodmanblair** [comment]
i mean, the lazy way to approach this issue would just be to not name the site awes0me.dev. Just name it awes0medev.com or something

**Comment by hgoodmanblair** [comment]
but that might not fix the problem
